[package]
authors = ["Ken Esparta"]
edition = "2021"
name = "listener"
version = "0.1.0"
readme = "README.md"

[dependencies]
btleplug = "0.11"
tokio = { version = "1.0", features = ["full"] }
uuid = "1.0"
futures = "0.3"
