[target.thumbv7em-none-eabihf]
runner = "qemu-system-arm -cpu cortex-m4 -machine netduinoplus2 -nographic -semihosting-config enable=on,target=native -kernel"

[build]
target = "thumbv7em-none-eabihf"

[unstable]
build-std = ["core"]